name: Publish SSH Container

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Target platform for Docker image
        required: true
        default: linux/amd64

env:
  REGISTRY: ghcr.io

jobs:
  publish-ssh:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: leoriviera/contained-ssh

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ssh
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
