name: Publish SSH Container

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish-ssh:
    name: Build SSH image
    uses: ./.github/workflows/publish-image.yaml
    with:
      image_name: ssh-container
      docker_context: ./ssh
    secrets: inherit
    permissions:
      contents: read
      packages: write
