name: Publish container images

on:
  workflow_dispatch:
    inputs:
      SSH_IMAGE:
        description: The location of the SSH image to use
        required: true
        default: ghcr.io/leoriviera/contained-ssh:latest
      BLOG_GITHUB_REPO:
        description: The GitHub repository to use for the blog
        required: true
        default: https://github.com/leoriviera/blog

jobs:
  build-and-push-ssh:
    name: Build SSH image
    uses: ./.github/workflows/publish-image.yaml
    with:
      image_name: contained-ssh
      docker_context: ./packages/ssh
      build-args: |
        BLOG_GITHUB_REPO=${{ inputs.BLOG_GITHUB_REPO }}
    secrets: inherit
    permissions:
      contents: read
      packages: write
  build-and-push-server:
    name: Build server image
    uses: ./.github/workflows/publish-image.yaml
    with:
      image_name: contained-server
      docker_context: ./packages/server
      build-args: |
        SSH_IMAGE=${{ inputs.SSH_IMAGE }}
    secrets: inherit
    permissions:
      contents: read
      packages: write
