name: Publish container images

on:
  workflow_dispatch:

jobs:
  build-and-push-ssh:
    name: Build SSH image
    uses: ./.github/workflows/publish-image.yaml
    with:
      image_name: contained-ssh
      docker_context: ./packages/ssh
    secrets: inherit
    permissions:
      contents: read
      packages: write
  build-and-push-server:
    name: Build server image
    uses: ./.github/workflows/publish-image.yaml
    with:
      image_name: contained-server
      docker_context: ./packages/server
    secrets: inherit
    permissions:
      contents: read
      packages: write
